version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "15432:5432"

  redis:
    image: redis:rc-alpine3.12
    restart: always
    ports:
      - "16379:6379"

  web:
    build: .
    image: uzbbcbot:latest
    command: >
      sh -c "python manage.py makemigrations && \
        python manage.py migrate && \
        python manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env
    environment:
      PYTHONPATH: /uzbbcbot
    volumes:
      - .:/uzbbcbot
      - static_volume:/uzbbcbot/static/
      - media_volume:/uzbbcbot/media/
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    image: uzbbcbot:latest
    restart: always
    build: .
    env_file:
      - .env
    command: celery -A core worker -l info
    volumes:
      - .:/uzbbcbot
    depends_on:
      - web
      - redis

  celery-beat:
    image: uzbbcbot:latest
    restart: always
    build: .
    env_file:
      - .env
    command: celery -A core beat -l info
    volumes:
      - .:/uzbbcbot
    depends_on:
      - web

  bot:
    image: uzbbcbot:latest
    restart: always
    env_file:
      - .env
    command: python3 telegram_bot/app.py
    environment:
      PYTHONPATH: /uzbbcbot
    volumes:
      - .:/uzbbcbot
    depends_on:
      - web
      - redis

volumes:
  static_volume:
  media_volume:
