# Dockerfile.bot (с supervisord)

FROM python:3.10.12

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Установка supervisor
RUN apt-get update && apt-get install -y supervisor

COPY telegram_bot/ /app
COPY supervisord.conf /etc/supervisord.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
