languages = {
    "uz": {
        "start_command": "👋 Assalomu aleykum",
        "set_lang_handler": "⚙️ Tilni tanlang:",
        "get_phone_number_handler": "☎️ Telefon raqamingizni yuboring",
        "choose_region_handler": "🌇 Viloyatni tanlang",
        "choose_city_handler": "🌇 Tumani tanlang",
        "verify_code_text": "🔢 Sms dagi kodni kiriting:",
        "wrong_code_text": "⚠️ Noto`g`ri kod",
        "profile_text": "🆔 <code>{}</code>\n👤 <b>{}</b>\n🌇 <b>{}</b>\n☎️ <code>{}</code>",
        "location_text": "Lokatsiyani yuboring",
        "service_info_text": "<b>Ism:</b> {}\n<b>Soxasi:</b> {}\n<b>Narxi:</b> {} UZS\n<b>Viloyati:</b> {}\n\n{} km",

        "reply_button": {
            "service_text": "Xizmatlar",
            "product_text": "Mahsulotlar",
            "about_text": "ℹ️ Bot Xaqida",
            "admin_text": "👤 Bot Admini",
            "phone_number_text": "📞 Telefon raqam",
            "profile_text": "💼 Profil",
            "edit_user_info": "⚙️ Malumotlarni o`zgartirish",
            "edit_language_text": "⚙️ Tilni o`zgartirish",
            "back_text": "🔙 Ortga",
            "location_text": "📍 Mening lokatsiyam",
            "call_text": "📞 {}",
            "only_uzbekistan": "📍 Uzbekiston bo`ylab",
        }
    },
    "ru": {
        "start_command": "👋 Здравствуйте",
        "set_lang_handler": "⚙️ Выберите язык:",
        "get_phone_number_handler": "☎️ Отправьте телефон немор",
        "choose_region_handler": "🌇 Выьерите регион",
        "choose_city_handler": "🌇 Выберите город",
        "verify_code_text": "🔢 Введите смс код:",
        "wrong_code_text": "⚠️ Неверный смс код",
        "profile_text": "🆔 <code>{}</code>\n👤 <b>{}</b>\n🌇 <b>{}</b>\n☎️ <code>{}</code>",
        "location_text": "Отправьте локацию",
        "service_info_text": "<b>Имя:</b> {}\n<b>Профессия:</b> {}\n<b>Цена:</b> {} UZS\n<b>Область:</b> {}\n\n{} km",

        "reply_button": {
            "service_text": "Сервисы",
            "product_text": "Продукты",
            "about_text": "ℹ️ О боте",
            "admin_text": "👤 Администратор",
            "phone_number_text": "📞 Номер телефона",
            "profile_text": "💼 Профиль",
            "edit_user_info": "⚙️ Изменить информацию",
            "edit_language_text": "⚙️ Изменить язык",
            "back_text": "🔙 Назад",
            "location_text": "📍 Моя локация",
            "call_text": "📞 {}",
            "only_uzbekistan": "📍 Весь Узбекистан",
        }
    },
    "en": {
        "start_command": "👋 Hello",
        "set_lang_handler": "⚙️ Choose a language",
        "get_phone_number_handler": "☎️ Send your phone number",
        "choose_region_handler": "🌇 Choose region",
        "choose_city_handler": "🌇 Choose city",
        "verify_code_text": "🔢 Enter sms code:",
        "wrong_code_text": "⚠️ Sms code is incorrect",
        "profile_text": "🆔 <code>{}</code>\n👤 <b>{}</b>\n🌇 <b>{}</b>\n☎️ <code>{}</code>",
        "location_text": "Send your location",
        "service_info_text": "<b>Name:</b> {}\n<b>Professional:</b> {}\n<b>Price:</b> {} UZS\n<b>Region:</b> {}\n\n{} km",

        "reply_button": {
            "service_text": "Services",
            "product_text": "Products",
            "about_text": "ℹ️ About",
            "admin_text": "👤 Admin",
            "phone_number_text": "📞 Phone number",
            "profile_text": "💼 Profile",
            "edit_user_info": "⚙️ Edit Info",
            "edit_language_text": "⚙️ Edit language",
            "back_text": "🔙 Back",
            "location_text": "📍 My location",
            "call_text": "📞 {}",
            "only_uzbekistan": "📍 Only Uzbekistan",
        }
    },
}
